kind: ConfigMap
apiVersion: v1
metadata:
  name: cse-credential
  namespace: default
data:
  certificate.yaml: |
    cse:
      credentials:
        accessKey: ak
        secretKey: sk
        akskCustomCipher: default  
