cse-config-order: 100

## Spring Boot configurations
server:
  port: 9091

spring:
  application:
    name: customer-website

## CSE configurations
servicecomb:
  service:
    application: dtm
    name: customer-website
    version: 0.0.2
    registry:
      address: http://127.0.0.1:30100
    config:
      address: http://127.0.0.1:30113
  rest:
    address: 0.0.0.0:9091
    ## static web site will token root
    servlet:
      urlPattern: /api/*